# Generated by Django 5.2.6 on 2025-09-17 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('apparel', 'Apparel'), ('shoes', 'Shoes'), ('outdoor', 'Outdoor'), ('ball', 'Ball'), ('racket', 'Racket'), ('accessories', 'Accessories'), ('supplements', 'Supplements'), ('others', 'Lainnya')], default='others', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(default='Flexora', max_length=50)),
            ],
        ),
    ]
