# Generated by Django 5.2.6 on 2025-09-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='main_product_uuid',
        ),
    ]
