# Generated by Django 5.2.6 on 2025-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fitness', 'Peralatan Fitness'), ('apparel', 'Pakaian Olahraga'), ('shoes', 'Sepatu Olahraga'), ('outdoor', 'Peralatan Outdoor'), ('ball_games', 'Peralatan Bola'), ('racket_games', 'Peralatan Raket'), ('accessories', 'Aksesori Olahraga'), ('supplements', 'Suplemen & Nutrisi'), ('others', 'Lainnya')], default='others', max_length=20),
        ),
    ]
