# Generated by Django 5.2.6 on 2025-10-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_employee_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
