# Generated by Django 5.2.6 on 2025-09-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Flexora', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('apparel', 'Apparel'), ('shoes', 'Shoes'), ('outdoor', 'Outdoor'), ('ball', 'Ball'), ('racket', 'Racket'), ('accessories', 'Accessories'), ('supplements', 'Aupplements'), ('others', 'Lainnya')], default='others', max_length=20),
        ),
    ]
