# Generated by Django 5.2.6 on 2025-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('apparel', 'Apparel'), ('shoes', 'Shoes'), ('outdoor', 'Outdoor'), ('ball', 'Ball'), ('racket', 'Racket'), ('accessories', 'Accessories'), ('supplements', 'Supplements'), ('others', 'Lainnya')], default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
